#!/usr/bin/env bash
#
# build all the things
#

source common.inc

function buildjob() {
	gcc -v
	[ -f Configure ] 	&& ./Configure
	./config		|| return
	time make -j$(nproc)	|| return
	[ -f util/selftest.pl ] && perl util/selftest.pl
	return 0
}

timestamp=$(date --rfc-3339=seconds | sed 's/ /_/')
echo "${banner} full log in work/OPENSSLDIR/buildlog-${timestamp}.log"
for dir in work/openssl*/; do
	echo -ne "\tbuilding in ${dir} "
	cd ${dir}
	buildjob &> buildlog-${timestamp}.log
	if [ "$?" -gt 0 ]; then
		echo -e "\t\t$(bold FAIL)"
	else
		echo -e "\t\t$(bold DONE)"
	fi
	cd - &>/dev/null
done

