#!/usr/bin/env bash
#
# build all the things
#

source common.inc

timestamp=$(date --rfc-3339=seconds | sed 's/ /_/')
for folder in work/openssl*/; do
	echo -ne "${banner} building in ${folder}"
	time (	
		cd ${folder}
		gcc -v
		[[ -f ./Configure ]] && ./Configure
		./config 	|| echo "configure failed"
		make -j$(nproc)	|| echo "compilation failed"
	) &> ${folder}/buildlog-${timestamp}.log \
	  || fail "compilation of ${folder} failed"
	wait
	echo -e "\t\t$(tput bold)DONE$(tput sgr0)"
done

