#!/usr/bin/env bash
#
# Clean all build directories
#

source common.inc

[ -d work ] || fail "no 'work/' directory exists"

for dir in work/*/; do
	echo -ne "\tcleaning ${dir} "
	cd ${dir}
	make clean && echo -e "\t\t$(bold DONE)"
	cd - &>/dev/null
done

