#!/usr/bin/env bash
#
# Clean all build directories
#

source lib/common.inc

[ -d work ] || fail "no 'work/' directory exists"

for dir in work/*/; do
	echo -ne "\tcleaning ${dir} "
	cd ${dir}
	make clean &>/dev/null 
	echo -e "\t\t$(bold CLEAN) (where possible)"
	cd - &>/dev/null
done

